package com.dev3mk.awraqi.util

object Constants {
    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
    const val UPDATE_URL = "https://play.google.com/store/apps/details?id=com.dev3mk.awraqi"
    const val CURRENT_VERSION = "1.4.5"
    const val DATA_STORE_EMAIL= "DATA_STORE_EMAIL"
    const val DATA_STORE_NIGHT_MODE = "DATA_STORE_NIGHT_MODE"
    const val EMAIL_KEY = "EMAIL_KEY"
    const val FIRE_STORE_USERS_COLLECTION = "USERS"
    const val FIRE_STORE_ADMIN_COLLECTION = "ADMINS"
    const val FIRE_STORE_BOOKS_COLLECTION = "BOOKS"
    const val FIRE_STORE_USER_BOOKS_COLLECTION = "USER_BOOKS_COLLECTION"
    const val SERVICE_INTENT_NAME = "SERVICE_INTENT_NAME"
    const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION_CHANNEL_ID"
    const val DOWNLOAD_NOTIFICATION_CHANNEL_NAME = "DOWNLOAD_NOTIFICATION_CHANNEL_NAME"
    const val DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    const val DOWNLOAD_CANCELED = "DOWNLOAD_CANCELED"
    const val SUPPORT_EMAIL = "awraqi.help@gmail.com"
    const val DOWNLOAD_PROGRESS_KEY= "DOWNLOAD_PROGRESS_KEY"
    const val USER_FAVORITES_COLLECTION = "USER_FAVORITES_COLLECTION"
    const val FIRE_STORE_VERSION = "VERSION"

}

