package com.example.waraq.util

object Constants {
    const val DATA_STORE_USER_TYPE = "DATA_STORE_USER_TYPE"
    const val DATA_STORE_EMAIL= "DATA_STORE_EMAIL"
    const val DATA_STORE_LANGUAGE = "DATA_STORE_LANGUAGE"
    const val DATA_STORE_NIGHT_MODE = "DATA_STORE_NIGHT_MODE"
    const val USER_TYPE = "USER_TYPE"
    const val EMAIL_KEY = "EMAIL_KEY"
    const val ADMIN_USER_TYPE = "ADMIN_USER_TYPE"
    const val STUDENT_USER_TYPE = "STUDENT_USER_TYPE"
    const val FIRE_STORE_USERS_COLLECTION = "USERS"
    const val FIRE_STORE_ADMIN_COLLECTION = "ADMINS"
    const val FIRE_STORE_BOOKS_COLLECTION = "BOOKS"
    const val FIRE_STORE_USER_BOOKS_COLLECTION = "USER_BOOKS_COLLECTION"
    const val SERVICE_INTENT_NAME = "SERVICE_INTENT_NAME"
    const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION_CHANNEL_ID"
    const val DOWNLOAD_NOTIFICATION_CHANNEL_NAME = "DOWNLOAD_NOTIFICATION_CHANNEL_NAME"
    const val DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    const val DOWNLOAD_CANCELED = "DOWNLOAD_CANCELED"
    const val SUPPORT_EMAIL = "mohamed.elkholy14920@gmail.com"
    const val DOWNLOAD_PROGRESS_ACTION = "com.example.DOWNLOAD_PROGRESS_ACTION"
    const val DOWNLOAD_TITLE_KEY= "DOWNLOAD_TITLE_KEY"
    const val DOWNLOAD_PROGRESS_KEY= "DOWNLOAD_PROGRESS_KEY"

}

