package com.example.waraq.util

object Constants {
    const val DEFAULT_SHARED_PREFERENCES = "DEFAULT_SHARED_PREFERENCES"
    const val USER_TYPE = "USER_TYPE"
    const val EMAIL_KEY = "EMAIL_KEY"
    const val ADMIN_USER_TYPE = "ADMIN_USER_TYPE"
    const val STUDENT_USER_TYPE = "STUDENT_USER_TYPE"
    const val FIRE_STORE_STUDENT_COLLECTION = "STUDENTS"
    const val FIRE_STORE_ADMIN_COLLECTION = "ADMINS"
    const val FIRE_STORE_BOOKS_COLLECTION = "BOOKS"
    const val SERVICE_INTENT_NAME = "SERVICE_INTENT_NAME"
    const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION_CHANNEL_ID"
    const val DOWNLOAD_NOTIFICATION_CHANNEL_NAME = "DOWNLOAD_NOTIFICATION_CHANNEL_NAME"
    const val DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    const val DOWNLOAD_CANCELED = "DOWNLOAD_CANCELED"

}

